import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
   flatListPadding: {
    marginTop: 0,
  },
  cartItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#E9C46A60',
    borderRadius: 15,
    marginBottom: 15,
    marginHorizontal: 15,
    borderWidth: 0,
  },
  cartItemImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 15,
    backgroundColor: '#eee',
  },
  cartItemDetails: {
    flex: 1,
    justifyContent: 'center',
  },
  cartItemName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  cartItemDescription: {
    fontSize: 14,
    color: '#888',
    marginBottom: 5,
  },
  priceAndRemove: {
    alignItems: 'flex-end',
    minWidth: 80,
  },
  cartItemPrice: {
    fontSize: 20,
    fontWeight: '900',
    color: '#333',
    marginBottom: 10,
  },
  quantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  controlButton: {
    width: 25,
    height: 25,
    borderRadius: 12.5,
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 5,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  controlText: {
    fontSize: 18,
    lineHeight: 22,
    color: '#333',
    fontWeight: 'bold',
  },
  quantityText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    minWidth: 10,
    textAlign: 'center',
  },
  notesContainer: {
    paddingHorizontal: 15,
    marginBottom: 5,
  },
  notesInput: {
    height: 50,
    width: '100%',
    backgroundColor: 'white',
    borderRadius: 8,
    padding: 10,
    textAlignVertical: 'top',
    fontSize: 13,
    borderColor: '#E9C46A',
    borderWidth: 1,
  },
  divider: {
    height: 0,
    borderBottomWidth: 0,
    borderStyle: 'dashed',
    borderColor: 'transparent',
    backgroundColor: 'transparent',
    marginBottom: 0,
    marginHorizontal: 0,
  },
  footerContainer: {
    padding: 20,
    borderTopWidth: 0,
    borderTopColor: 'transparent',
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 3,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  totalLabel: {
    fontSize: 20,
    fontWeight: '900',
    color: '#333',
  },
  totalValue: {
    fontSize: 22,
    fontWeight: '900',
    color: '#264653',
  },
  confirmButton: {
    backgroundColor: '#4CB58F',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
  },
  confirmButtonDisabled: {
    backgroundColor: '#99B8AD',
  },
  confirmButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  emptyCartContainer: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderRadius: 10,
    marginTop: 20,
    borderWidth: 1,
    borderColor: '#eee',
  },
  emptyCartText: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  emptyCartSubText: {
    fontSize: 14,
    color: '#888',
    textAlign: 'center',
  },
  backButtonHeader: {
    marginRight: 10,
  },
  modalBackground: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center'
  },
  modalContent: {
    backgroundColor: '#fff',
    padding: 30,
    borderRadius: 12,
    width: '80%',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  modalMessage: {
    textAlign: 'center',
    color: '#666',
    marginBottom: 20,
  },
  modalRemoveButton: {
    backgroundColor: '#D63031',
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
    marginBottom: 10,
  },
  modalButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  modalCancelButton: {
    backgroundColor: '#f0f0f0',
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ccc',
  },
  modalCancelButtonText: {
    color: '#333',
    fontWeight: 'bold',
  },
  modalCloseButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    padding: 5,
  },
});

export default styles;